import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useState, useEffect } from "react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Auth state for navbar
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  useEffect(() => {
    const token =
      typeof window !== "undefined"
        ? localStorage.getItem("feez_token")
        : null;
    setIsAuthenticated(!!token);
  }, []);
  const handleLogout = () => {
    localStorage.removeItem("feez_token");
    setIsAuthenticated(false);
    alert("Logged out successfully!");
    window.location.href = "/";
  };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Global Navigation Bar */}
        <nav className="w-full overflow-x-auto flex flex-col md:flex-row justify-between items-center py-4 px-2 mb-8 bg-gray-800 rounded-xl shadow-lg">
          <div className="text-3xl font-extrabold tracking-wide mb-2 md:mb-0">
            FEEZ
          </div>
          <div className="flex gap-4 md:gap-6 items-center flex-nowrap">
            <Link
              href="/"
              className="text-xl md:text-2xl font-bold px-4 py-2 rounded-lg hover:bg-blue-700 transition-all"
            >
              LOGIN
            </Link>
            <Link
              href="/public"
              className="text-xl md:text-2xl font-bold px-4 py-2 rounded-lg hover:bg-blue-700 transition-all"
            >
              PUBLIC
            </Link>
            {isAuthenticated && (
              <Link
                href="/dashboard"
                className="text-xl md:text-2xl font-bold px-4 py-2 rounded-lg bg-yellow-600 hover:bg-yellow-700 transition-all"
              >
                DASHBOARD
              </Link>
            )}
            {isAuthenticated && (
              <button
                onClick={handleLogout}
                className="text-xl md:text-2xl font-bold px-4 py-2 rounded-lg bg-red-600 hover:bg-red-700 transition-all"
              >
                LOGOUT
              </button>
            )}
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
